### ISSUE TITLE
有几个问题，合并成一个 issue

### ISSUE THREAD

**Issue by CliffHan** [dounine/wechat-pay-rust-sdk#3]
1. 这是微信官方的 sdk 吗？看命名像是，但又没在微信官方文档中提及。
2. 微信支付官方建议验证 timestamp 防止重放攻击，这个库里没有实现对吧。
3. 看起来代码中有好几处 signatrue 是写错了，应该是 signature
4. 代码中没有直接从 certificate 中提取 public key。考虑到官方提供的都是 certificate pem，能否增加一个转换？
    关于这一点，我可以给个简单例子，结合 pem 和 x509-parser 实现
```rust
    let pem = pem::parse(certificate_pem_file_str.as_bytes())?;
    let (_, cert) = x509_parser::parse_x509_certificate(pem.contents())?;
    Ok(RsaPublicKey::from_pkcs1_der(&cert.public_key().subject_public_key.data)?)
```

还有个跟这个库的实现无关的问题。
关于验签，是使用“平台证书”，而不是使用“API证书”，对吧。
就是说，“API证书”包含私钥和证书，是商户持有的；而“平台证书”是支付平台持有私钥，商户只能拿到证书验签，是这样吧。

**Comment by CliffHan** [comment]
还有一个疑问，从 API 设计来看，验签只是验证微信发来的 notify request，不验 response？

**Comment by dounine** [comment]
首先在这里感谢您的建议与反馈。

1、微信官方没有出rust版本，是参照微信支付文档所写。
2、timestamp 防止重放攻击确实没有实现，您可以提交一个request。
3、signatrue命名错误已修正（0.2.15版本）
4、证书中提取公钥功能已实现，例子已出使用说明。
5、验签是使用的平台证书，先使用api读取平台证书再进行验签。

**Comment by CliffHan** [comment]
感谢您的工作，微信官方文档关于验签部分没说太清楚，昨天我调试了一天都是验签失败，看到您的代码才看明白是我用错了证书。

timestamp 的问题我其实写了一个简单函数做验证，由于这里涉及到库 api 设计的问题，不是 bug fix，我就不提交 request 了。代码给出做参考。

```rust
fn verify_timestamp(timestamp: &str) -> Result<bool, anyhow::Error> {
    let timestamp_value: i64 = timestamp.parse()?;
    let timestamp_now = chrono::offset::Local::now().timestamp();
    Ok(timestamp_now <= timestamp_value + 300/* in 5 minutes */)
}
```
